sudo: required

services:
  - docker

install:
  - docker build -t lgatica/mongorestore-s3:latest .

script:
  - docker run --rm lgatica/mongorestore-s3:latest mongorestore --version

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
deploy:
  provider: script
  script: docker push lgatica/mongorestore-s3:latest
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
